name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Nightly Toolchain
      run: rustup install nightly
    - name: Install Bootimage
      run: cargo install bootimage
    - name: Build Bootloader
      run: rustup run nightly cargo bootimage --release --config .cargo/config.toml
